### ISSUE TITLE
optimisation: infer types of local variables to reduce boxing

### ISSUE THREAD

**Issue by bamboo** [bamboo/idris-cil#13]
Currently, a function such as:

``` Idris
f : Double -> Double
f d = 3.0 + d * 42
```

Compiles down to the following boxing-heavy bytecode (nevermind the fact that Double is currently mapped to float32 which is a separate issue - #8):

``` il
.method static assembly object 'Main.f'(object 'e0') cil managed {
    .locals init (
            object l0,
            object l1)
    ldc.r4 3.0
    box float32
    stloc.0 
    ldc.r4 42.0
    box float32
    stloc.1 
    ldarg.0 
    unbox.any float32
    ldloc.1 
    unbox.any float32
    mul
    box float32
    stloc.1 
    ldloc.0 
    unbox.any float32
    ldloc.1 
    unbox.any float32
    add
    box float32
    ret
}
```

The type for both local variables could be inferred thus allowing all unnecessary boxing operations to be removed leaving only the unboxing of the argument and the final boxing of the return value.

**Comment by BartAdv** [comment]
I'm thinking about striping boxing/unboxing from various cgOps that do not know their context, for example `SConst`. This means lots of stuff will cease to work, and then the task will be to figure out what places will be in charge of performing boxing/unboxing (for example, `load` will have to be equipped with knowledge about type (or its equivalent should be implemented that would be used in places where we know the types)).

**Comment by bamboo** [comment]
I was thinking that a separate step that acted upon the generated IL could even try to specialise function signatures and call sites without adding much complexity to the code base.

**Comment by BartAdv** [comment]
#14 addresses it, however, it has its limitations, so let's go for type inference, but not on the IL level. Let's create additional intermediate representation, basically IRsimplified + type info we can infer. Then the code generator would work on this representation, and inference would be one pass before.

This could potentially allow US to not only have info about primitives, we could create some data structures to describe CIL complex types and use it to map SCon into more efficient types which would be used for SCon and SConCase.

**Comment by BartAdv** [comment]
I've started implementing inference basing on Stephen Diehl implementation, learning HM details along the way. Whats interesting is that it shall infer custom datatypes as well (as long as its deconstructed in Idris code) meaning we will be able to use this info to build better matching CIL structures for those. In FFI export user will just have to provide name (and possibly some options) - this name will get matched with inferred data type info, and it should allow for boilerplate-less data exports.

**Comment by BartAdv** [comment]
OK, just to keep you posted, as the progress on it is not that fast as I'd like but nonetheless I'm keep going. I think I've managed to get around the issues with APPLY and EVAL (which would have to remain untyped), and I am now producing the tree of type similar to `SExp`, but with type attached (in one pass, both primitives and the rest of the inference can be done in one step I think):

```
type TExp = (SExp', Type)
data SExp'
  = TSV LVar
  | TSApp Bool Name [LVar]
  | TSLet LVar TExp TExp
  | TSUpdate LVar TExp
  | TSCon (Maybe LVar)
          Int Name [LVar]
  | TSCase CaseType LVar [TSAlt]
  | TSChkCase LVar [TSAlt]
  | TSProj LVar Int
  | TSConst Const
  | TSForeign FDesc FDesc [(FDesc, LVar)]
  | TSOp PrimFn [LVar]
  | TSNothing
  | TSError String
    deriving Show

data TSAlt
  = TSConCase Int Int Name [Name] TExp
  | TSConstCase Const TExp
  | TSDefaultCase TExp
  deriving Show
```

I don't really like that I had to almost duplicate `SExp` one to one, but I don't know if I could do this differently.

I will test it further and cleanup the code.

**Comment by bamboo** [comment]
Thanks for the update, @BartAdv. I'm glad to hear you're making progress.

About the `SExp` duplication feel, I think `TExp` should be a little closer to IL than to `SExp`. For instance, `TSForeign` and `TSop` would not need to exist because they would be subsumed by `TSApp`.  The pipeline I have in mind would look something like: `SExp` --(elaboration)--> `TExp` --(type inference)--> `(TExp, TypeEnvironment)` --(codegen)-->  `language-cil`

**Comment by BartAdv** [comment]
Yeah, you're right, thanks for hints. I will check overall correctness with
current WIP TExp semantics and will ping you later again once I start
thinking what best semantics should be for that phase

**Comment by BartAdv** [comment]
Hm, taking another look on `cil :: SExp -> CilCodegen ()` it's not immediately obvious why one would want to avoid having separate Op/Foreign/App in the generation phase.

What possible new cases could be made:
* Special constructors: True, False
* ifThenElse

What else you had in mind?

**Comment by bamboo** [comment]
Resolved in a4c22ede5f6e05c055492b3f8a2d5d9c2583b4ac.

Check out the results for the bit population count function in [this gist](https://gist.github.com/bamboo/46044856bc2347afc6bd3f924531aa2d).

**Comment by BartAdv** [comment]
It's cool to see you're progressing with the project! Are you using it somewhere, or is it still at tinkering stage?

**Comment by bamboo** [comment]
Hey @BartAdv! Just writing some prototypes.
